import type { Workspace, ChatMessage, InsightCard, Report, GraphNode, Document } from "./types";

export const demoDocuments: Document[] = [
  {
    id: "doc-1",
    name: "Q3 Market Research Report.pdf",
    type: "pdf",
    size: 2400000,
    uploadedAt: new Date(Date.now() - 3600000 * 2),
    status: "ready",
    summary: "Comprehensive analysis of Q3 market trends in SaaS industry",
    topics: ["Market Growth", "Competitor Analysis", "Customer Trends"],
    wordCount: 8450,
  },
  {
    id: "doc-2",
    name: "Competitor Analysis - HubSpot.docx",
    type: "docx",
    size: 1200000,
    uploadedAt: new Date(Date.now() - 3600000 * 5),
    status: "ready",
    summary: "Deep dive into HubSpot's product strategy and market positioning",
    topics: ["Pricing", "Features", "Market Share"],
    wordCount: 4200,
  },
  {
    id: "doc-3",
    name: "Customer Interviews - Oct 2024.txt",
    type: "txt",
    size: 450000,
    uploadedAt: new Date(Date.now() - 3600000 * 24),
    status: "ready",
    summary: "Qualitative feedback from 24 customer interviews",
    topics: ["Pain Points", "Feature Requests", "Pricing Feedback"],
    wordCount: 12300,
  },
  {
    id: "doc-4",
    name: "SEO Performance Data.csv",
    type: "csv",
    size: 320000,
    uploadedAt: new Date(Date.now() - 3600000 * 48),
    status: "ready",
    summary: "12 months of organic search performance metrics",
    topics: ["SEO", "Traffic", "Keywords"],
    wordCount: 2100,
  },
  {
    id: "doc-5",
    name: "Industry Trends - Gartner.pdf",
    type: "pdf",
    size: 5100000,
    uploadedAt: new Date(Date.now() - 3600000 * 72),
    status: "ready",
    summary: "Gartner's annual report on enterprise software trends",
    topics: ["AI Adoption", "Cloud Migration", "Security"],
    wordCount: 18900,
  },
];

export const demoWorkspaces: Workspace[] = [
  {
    id: "ws-1",
    name: "Q4 Marketing Strategy",
    description: "Research and analysis for Q4 go-to-market strategy",
    createdAt: new Date(Date.now() - 86400000 * 7),
    updatedAt: new Date(Date.now() - 3600000 * 2),
    documents: demoDocuments,
    status: "active",
    healthScore: 87,
    tags: ["marketing", "strategy", "q4"],
  },
  {
    id: "ws-2",
    name: "Competitor Analysis 2024",
    description: "Comprehensive competitive landscape research",
    createdAt: new Date(Date.now() - 86400000 * 14),
    updatedAt: new Date(Date.now() - 86400000 * 2),
    documents: demoDocuments.slice(0, 3),
    status: "active",
    healthScore: 72,
    tags: ["competitors", "research"],
  },
  {
    id: "ws-3",
    name: "Product Launch Research",
    description: "Market validation and launch strategy research",
    createdAt: new Date(Date.now() - 86400000 * 30),
    updatedAt: new Date(Date.now() - 86400000 * 5),
    documents: demoDocuments.slice(1, 4),
    status: "active",
    healthScore: 94,
    tags: ["product", "launch"],
  },
];

export const demoChatMessages: ChatMessage[] = [
  {
    id: "msg-1",
    role: "user",
    content: "What are the main opportunities in our target market for Q4?",
    timestamp: new Date(Date.now() - 3600000),
  },
  {
    id: "msg-2",
    role: "assistant",
    content: "Based on your uploaded research, I've identified **3 key market opportunities** for Q4:\n\n1. **Enterprise SMB segment** — 67% of mid-market companies plan to increase SaaS spending in Q4, with AI-powered tools being the top priority.\n\n2. **Content automation demand** — Customer interviews reveal 78% of marketing teams are actively looking for AI research tools to replace manual workflows.\n\n3. **Competitive whitespace** — HubSpot and Salesforce have significant pricing gaps ($500-$2,000/mo) that mid-market teams find prohibitive.",
    timestamp: new Date(Date.now() - 3540000),
    confidence: 87,
    evidence: [
      { documentId: "doc-1", documentName: "Q3 Market Research Report.pdf", excerpt: "67% of mid-market companies plan to increase SaaS spending in Q4...", confidence: 92 },
      { documentId: "doc-3", documentName: "Customer Interviews - Oct 2024.txt", excerpt: "78% of marketing teams actively looking for AI research tools...", confidence: 88 },
      { documentId: "doc-2", documentName: "Competitor Analysis - HubSpot.docx", excerpt: "HubSpot Enterprise pricing starts at $1,200/month...", confidence: 95 },
    ],
    weaknesses: ["Revenue projection data unavailable for Q4 specifically"],
    contradictions: ["One interview source suggests 45% adoption rate, conflicting with survey data"],
    missingInfo: ["Competitive pricing data for Notion AI", "Recent churn rates from competitors"],
    nextQuestion: "Would you like me to analyze the specific pricing strategy that could capture this whitespace?",
  },
  {
    id: "msg-3",
    role: "user",
    content: "What are the main risks we should be aware of?",
    timestamp: new Date(Date.now() - 3000000),
  },
  {
    id: "msg-4",
    role: "assistant",
    content: "I've analyzed your documents and found **4 significant risks** you should address before Q4 launch:\n\n**High Priority:**\n1. **Market saturation risk** — 12 new AI research tools launched in the past 6 months in your target space.\n\n**Medium Priority:**\n2. **Enterprise sales cycle** — Average B2B sales cycle of 3-6 months means Q4 pipeline needs to be built now.\n3. **Data privacy concerns** — 64% of enterprise buyers cite data handling as top concern for AI tools.\n\n**Lower Priority:**\n4. **Integration ecosystem** — Customers expect Notion, Slack, and Google Workspace integrations at launch.",
    timestamp: new Date(Date.now() - 2940000),
    confidence: 79,
    evidence: [
      { documentId: "doc-1", documentName: "Q3 Market Research Report.pdf", excerpt: "12 new AI research tools entered the market in H1 2024...", confidence: 85 },
      { documentId: "doc-5", documentName: "Industry Trends - Gartner.pdf", excerpt: "64% of enterprise buyers cite data privacy as primary concern...", confidence: 91 },
    ],
    weaknesses: ["Competitive launch timeline data is 6 months old"],
    missingInfo: ["Specific competitor feature comparison", "Customer acquisition cost benchmarks"],
    nextQuestion: "Should I generate a risk mitigation strategy based on these findings?",
  },
];

export const demoInsights: InsightCard[] = [
  {
    id: "ins-1",
    type: "opportunity",
    title: "Mid-market pricing gap identified",
    description: "Analysis reveals $200-500/mo pricing tier is underserved — 3 of your 5 competitor have no offering in this range, yet 45% of surveyed companies sit in this budget.",
    priority: "high",
    businessImpact: "high",
    evidence: ["Q3 Market Research Report.pdf", "Competitor Analysis - HubSpot.docx"],
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: "ins-2",
    type: "risk",
    title: "Sales cycle timing conflict",
    description: "Q4 launch timeline conflicts with typical 3-6 month enterprise sales cycles. Early Q4 pipeline must be initiated now for year-end revenue impact.",
    priority: "high",
    businessImpact: "high",
    evidence: ["Industry Trends - Gartner.pdf"],
    createdAt: new Date(Date.now() - 7200000),
  },
  {
    id: "ins-3",
    type: "trend",
    title: "AI research tool adoption accelerating",
    description: "84% increase in AI research tool adoption YoY in the SaaS sector. Early movers gaining significant market share before the space commoditizes.",
    priority: "medium",
    businessImpact: "high",
    evidence: ["Q3 Market Research Report.pdf", "Industry Trends - Gartner.pdf"],
    createdAt: new Date(Date.now() - 10800000),
  },
  {
    id: "ins-4",
    type: "contradiction",
    title: "Conflicting adoption rate data",
    description: "Customer interviews suggest 45% AI tool adoption, while market survey data from the same period indicates 67%. Discrepancy may reflect recency or sampling bias.",
    priority: "medium",
    businessImpact: "medium",
    evidence: ["Customer Interviews - Oct 2024.txt", "Q3 Market Research Report.pdf"],
    createdAt: new Date(Date.now() - 14400000),
  },
  {
    id: "ins-5",
    type: "missing",
    title: "Competitive pricing data incomplete",
    description: "Notion AI and Perplexity Enterprise pricing unavailable in current research. Pricing strategy decisions should be deferred until this data is collected.",
    priority: "medium",
    businessImpact: "medium",
    evidence: [],
    createdAt: new Date(Date.now() - 18000000),
  },
  {
    id: "ins-6",
    type: "action",
    title: "Launch content marketing campaign now",
    description: "Based on 78% demand signal from customer interviews + current market timing, a content marketing campaign targeting mid-market should begin immediately.",
    priority: "high",
    businessImpact: "high",
    evidence: ["Customer Interviews - Oct 2024.txt", "SEO Performance Data.csv"],
    createdAt: new Date(Date.now() - 21600000),
  },
];

export const demoGraphNodes: GraphNode[] = [
  { id: "n-1", label: "Marketing Strategy", type: "topic", x: 50, y: 50, connections: ["n-2", "n-3", "n-5"] },
  { id: "n-2", label: "SEO & Content", type: "topic", x: 25, y: 30, connections: ["n-1", "n-4"] },
  { id: "n-3", label: "Competitor Analysis", type: "topic", x: 75, y: 30, connections: ["n-1", "n-6", "n-7"] },
  { id: "n-4", label: "Keyword Strategy", type: "insight", x: 10, y: 55, connections: ["n-2"] },
  { id: "n-5", label: "Customer Pain Points", type: "insight", x: 50, y: 75, connections: ["n-1", "n-8"] },
  { id: "n-6", label: "HubSpot", type: "entity", x: 65, y: 15, connections: ["n-3"] },
  { id: "n-7", label: "Pricing Gap", type: "opportunity", x: 88, y: 50, connections: ["n-3", "n-5"] },
  { id: "n-8", label: "AI Adoption", type: "trend", x: 35, y: 88, connections: ["n-5"] },
];

export const demoReports: Report[] = [
  {
    id: "rep-1",
    type: "executive",
    persona: "ceo",
    title: "Q4 Strategic Overview — Executive Summary",
    content: "## Executive Summary\n\nBased on comprehensive analysis of 5 research documents, InsightFlow AI has identified significant market opportunity in Q4...",
    status: "approved",
    createdAt: new Date(Date.now() - 86400000),
    workspaceId: "ws-1",
  },
  {
    id: "rep-2",
    type: "marketing",
    persona: "marketing",
    title: "Q4 Marketing Campaign Brief",
    content: "## Marketing Brief\n\nTarget audience analysis reveals mid-market SaaS companies (50-500 employees) as primary segment...",
    status: "review",
    createdAt: new Date(Date.now() - 43200000),
    workspaceId: "ws-1",
  },
  {
    id: "rep-3",
    type: "swot",
    persona: "ceo",
    title: "SWOT Analysis — Market Position",
    content: "## SWOT Analysis\n\n**Strengths:** Unique evidence-based AI approach, transparent confidence scoring...",
    status: "draft",
    createdAt: new Date(Date.now() - 21600000),
    workspaceId: "ws-1",
  },
];
